name: TOROpassICsystem
version: 1.5
main: prj.salmon.toropassicsystem.TOROpassICsystem
api-version: 1.20
commands:
  charge:
    description: "ICカードに金額をチャージします"
    usage: "/charge [金額]"
  autocharge:
    description: "ICカードにオートチャージを設定します"
    usage: "/autocharge [いくらを下回ったとき] [チャージ額] または /autocharge stop"
  writecard:
    description: "ICカードに定期券情報を書き込みます"
    usage: "TOROpassの発売機で定期券データをコピーし、Minecraft内で貼り付けて実行してください"
  toropassrank:
    description: "TOROpassを使って移動した距離のランキングを表示します"
    usage: "/toropassrank を打ち込むだけです"
permissions:
  toropassicsystem.charge:
    description: "チャージコマンドの使用を許可します"
    default: true
  toropassicsystem.autocharge:
    description: "オートチャージ設定の使用を許可します"
    default: true
  toropassicsystem.writecard:
    description: "定期券情報の書き込みを許可します"
    default: true
  toropassicsystem.toropassrank:
    description: "TOROpass利用量ランキングの閲覧を許可します"
    default: true


