name: TOROpassICsystem
version: 1.3
main: prj.salmon.toropassicsystem.TOROpassICsystem
api-version: 1.20
commands:
  charge:
    description: "ICカードに金額をチャージします"
    usage: "/charge [金額]"
  autocharge:
    description: "ICカードにオートチャージを設定します"
    usage: "/autocharge [いくらを下回ったとき] [チャージ額] または /autocharge stop"
permissions:
  toropassicsystem.charge:
    description: "チャージコマンドの使用を許可します"
    default: true
  toropassicsystem.autocharge:
    description: "オートチャージ設定の使用を許可します"
    default: true
